[package]
name = "coin"
version = "0.1.0"
authors = ["laurent"]

[dependencies]
chrono = "0.4"
env_logger = "0.4.3"
log = "0.3.8"
serde = "1.0.23"
serde_derive = "1.0.23"
serde_json = "1.0.7"

[dependencies.ws]
version = "0.7.3"
features = ["ssl"]
